# Generated by Django 3.2.1 on 2021-05-14 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'app_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaOrdenPedido',
            fields=[
                ('id_consulta_op', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'consulta_orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id_descarga', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('formato_descarga', models.CharField(max_length=20)),
                ('fecha_descarga', models.DateField()),
            ],
            options={
                'db_table': 'descarga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoHabitacion',
            fields=[
                ('disponible', models.CharField(max_length=1)),
                ('no_disponible_asignada', models.CharField(max_length=1)),
                ('habitacion_id_habitacion', models.CharField(max_length=20)),
                ('estado_habitacion_id', models.FloatField(primary_key=True, serialize=False)),
                ('no_disponible_mantenimiento', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'estado_habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('transaccion_id_transaccion', models.CharField(max_length=50)),
                ('fecha_factura', models.DateField()),
                ('detalle', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_habitacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=20)),
                ('tipo_cama', models.CharField(max_length=20)),
                ('caracteristicas', models.CharField(max_length=50)),
                ('accesorios', models.CharField(max_length=50)),
                ('estado_habitacion_estado_habitacion_id', models.FloatField()),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impresion',
            fields=[
                ('id_impresion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('formato_impresion', models.CharField(max_length=20)),
                ('fecha_impresion', models.DateField()),
            ],
            options={
                'db_table': 'impresion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('credito', models.CharField(max_length=50)),
                ('debito', models.CharField(max_length=50)),
                ('transaccion_id_transaccion', models.CharField(max_length=50)),
                ('mÚtodo_pago_id', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_compra', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_orden_compra', models.DateField()),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id_pedido', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('recepcion_producto_id_recepcion_producto', models.CharField(max_length=20)),
                ('fecha_orden_pedido', models.DateField()),
            ],
            options={
                'db_table': 'orden_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('precio', models.BigIntegerField()),
                ('tipo_producto', models.CharField(max_length=20)),
                ('stock', models.CharField(max_length=20)),
                ('stock_critico', models.CharField(max_length=20)),
                ('fech_venc', models.BigIntegerField()),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepcionProducto',
            fields=[
                ('id_recepcion_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('orden_pedido_id_pedido', models.CharField(max_length=20)),
                ('fecha_recepcion_pro', models.DateField()),
            ],
            options={
                'db_table': 'recepcion_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id_registro', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cuenta_id_cuenta', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroComedor',
            fields=[
                ('id_menu', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('precio_menu', models.BigIntegerField()),
                ('tipo_plato', models.CharField(max_length=20)),
                ('tipo_servicio', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'registro_comedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionClienteReserva',
            fields=[
                ('cliente_rut', models.OneToOneField(db_column='cliente_rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.cliente')),
            ],
            options={
                'db_table': 'relacion_cliente_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudDeServicio',
            fields=[
                ('id_solicitud', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'solicitud_de_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('factura_id_factura', models.CharField(max_length=20)),
                ('mÚtodo_pago_mÚtodo_pago_id', models.FloatField()),
                ('fecha_transaccion', models.DateField()),
            ],
            options={
                'db_table': 'transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fech_nac', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('cuenta_id_cuenta', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('id_adm', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('id_emp', models.CharField(max_length=100, unique=True)),
                ('tipo_emp', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.usuario')),
                ('id_proveedor', models.CharField(max_length=20, unique=True)),
                ('emp_proveedor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionProductoOrdenpedido',
            fields=[
                ('orden_pedido_id_pedido', models.OneToOneField(db_column='orden_pedido_id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.ordenpedido')),
            ],
            options={
                'db_table': 'relacion_producto_ordenpedido',
                'managed': False,
            },
        ),
    ]
